"""JMAフィルタ Y(f) を近似する線形位相FIRの設計。

ファームウェアのリアルタイム震度はこの係数をそのまま使う。
振幅応答をそのまま再現する（正規化しない）ので、フィルタ後の絶対gal値が
FFT版と一致し、計測震度の絶対値がずれない。

numtaps を大きくするほど低周波（0.5Hz付近）の再現が良くなるが、
群遅延 = (numtaps-1)/2 サンプルぶんの速報遅延が増える。
100Hz・511tapで約2.55秒。リアルタイム震度の性質上この程度の遅延は許容する。
"""

from __future__ import annotations

import numpy as np
from scipy.signal import firwin2

from .filters import jma_filter_response

DEFAULT_NUMTAPS = 511


def design_fir(fs: float, numtaps: int = DEFAULT_NUMTAPS) -> np.ndarray:
    """Y(f) の振幅を再現するFIR係数を返す。"""
    if numtaps % 2 == 0:
        raise ValueError("numtaps は奇数（type-I 線形位相）にすること")
    nyq = fs / 2.0
    # 0..nyq を密にサンプルして目標振幅を作る
    grid = np.linspace(0.0, nyq, 2048)
    gain = jma_filter_response(grid)
    # firwin2 は freq[0]=0, freq[-1]=nyq を要求。DC/nyq のgainは実質0。
    gain[0] = 0.0
    taps = firwin2(numtaps, grid, gain, fs=fs)
    # DCゲインを厳密に0にする。firwin2 は 0.5Hz手前の急峻な立ち上がりを
    # 有限tapで解像しきれず、H(0)=sum(taps) が僅かに残る。これを消さないと
    # 重力(約1g=980gal)のDCが残留ゲインぶん漏れてストリーミング震度が跳ねる。
    # 平均を引くのは通過域の応答をほぼ変えずにDC成分だけ除く標準的な手法。
    taps = taps - taps.mean()
    return taps


def group_delay_samples(numtaps: int = DEFAULT_NUMTAPS) -> int:
    return (numtaps - 1) // 2


def export_c_array(taps: np.ndarray, name: str = "kJmaFirTaps") -> str:
    """FIR係数を C++ の float 配列リテラルとして出力する。"""
    lines = [f"// auto-generated by tools/jismo/fir.py — {taps.size} taps"]
    lines.append(f"static const int kJmaFirNumTaps = {taps.size};")
    lines.append(f"static const float {name}[{taps.size}] = {{")
    for i in range(0, taps.size, 6):
        chunk = ", ".join(f"{v:.9e}f" for v in taps[i:i + 6])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)
